name: Deployment pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
        types: [opened, synchronize]

jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Install dependencies
              run: npm run install:all
            #- name: Check style
            #  run: npm run eslint
            - name: Build
              working-directory: ./frontend/
              run: npm run build
            # environment variables
            - name: Run backend tests
              working-directory: ./backend/
              env:
                  MONGODB_URI: ${{ secrets.MONGODB_URI }}
                  MONGODB_URI_TEST: ${{ secrets.MONGODB_URI_TEST }}
                  SECRET: ${{ secrets.SECRET }}
                  NODE_ENV: test
              run: npm test
    # tag_release:
    #     needs: [simple_deployment_pipeline]
    #     runs-on: ubuntu-22.04
    #     if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    #     steps:
    #         - name: Checkout Code
    #           uses: actions/checkout@v4
    #         - name: Bump version and push tag
    #           uses: anothrNick/github-tag-action@1.64.0
    #           env:
    #               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #               DEFAULT_BUMP: patch
